project_id = "kzxqhtdxjyuktrghzmsp"

[functions.register]
verify_jwt = false

[functions.login]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.process-exam-pdf]
verify_jwt = false
